"use client";

import { FormEvent, useState } from "react";
import Link from "next/link";

type Profile = Record<string, string>;
export function MemberDashboardClient({ profile }: { profile: Profile }) {
  const [values, setValues] = useState(profile); const [message, setMessage] = useState(""); const [passwordMessage, setPasswordMessage] = useState("");
  async function saveProfile(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const response = await fetch("/api/member/profile", { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify(values) }); const data = await response.json(); setMessage(data.message || "Không thể cập nhật."); }
  async function changePassword(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = new FormData(event.currentTarget); const response = await fetch("/api/member/password", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ currentPassword: form.get("currentPassword"), nextPassword: form.get("nextPassword") }) }); const data = await response.json(); setPasswordMessage(data.message || "Không thể đổi mật khẩu."); if (response.ok) event.currentTarget.reset(); }
  const fields = [["name", "Tên doanh nghiệp"], ["industry", "Lĩnh vực hoạt động"], ["address", "Địa chỉ"], ["phone", "Điện thoại"], ["email", "Email"], ["website", "Website"], ["logo", "Link logo"], ["coverImage", "Link ảnh bìa"], ["introImage", "Link ảnh giới thiệu"], ["companyTagline", "Thông điệp doanh nghiệp"]] as const;
  return <section className="mt-7 grid gap-5 lg:grid-cols-2"><details className="rounded-[1.6rem] border border-slate-200 bg-white p-5 shadow-sm"><summary className="cursor-pointer text-lg font-semibold text-slate-950">Chỉnh sửa hồ sơ doanh nghiệp</summary><p className="mt-2 text-sm leading-6 text-slate-600">Quý hội viên có thể cập nhật logo và thông tin giới thiệu. Giấy phép kinh doanh hoặc mã số thuế cần Văn phòng BIHUBA xác minh.</p><form onSubmit={saveProfile} className="mt-5 grid gap-3 sm:grid-cols-2">{fields.map(([key, label]) => <label key={key} className={key === "address" || key === "companyTagline" ? "sm:col-span-2" : ""}><span className="mb-1 block text-xs font-semibold text-slate-600">{label}</span><input value={values[key] || ""} onChange={(event) => setValues((current) => ({ ...current, [key]: event.target.value }))} className="w-full rounded-xl border border-slate-200 px-3 py-2 text-sm text-slate-950"/></label>)}<button className="rounded-full bg-[#0E4FAF] px-5 py-3 text-sm font-semibold text-white sm:col-span-2">Lưu thay đổi</button></form>{message ? <p className="mt-3 text-sm text-cyan-700">{message}</p> : null}</details><div className="space-y-5"><details className="rounded-[1.6rem] border border-slate-200 bg-white p-5 shadow-sm"><summary className="cursor-pointer text-lg font-semibold text-slate-950">Đổi mật khẩu</summary><form onSubmit={changePassword} className="mt-5 space-y-3"><input required name="currentPassword" type="password" placeholder="Mật khẩu hiện tại" className="w-full rounded-xl border border-slate-200 px-3 py-2 text-slate-950"/><input required name="nextPassword" minLength={8} type="password" placeholder="Mật khẩu mới (ít nhất 8 ký tự)" className="w-full rounded-xl border border-slate-200 px-3 py-2 text-slate-950"/><button className="rounded-full border border-[#0E4FAF] px-5 py-2.5 text-sm font-semibold text-[#0E4FAF]">Đổi mật khẩu</button></form>{passwordMessage ? <p className="mt-3 text-sm text-cyan-700">{passwordMessage}</p> : null}</details><article className="rounded-[1.6rem] border border-amber-200 bg-amber-50 p-5"><h2 className="text-lg font-semibold text-slate-950">Giấy phép kinh doanh</h2><p className="mt-2 text-sm leading-6 text-slate-600">Để thay đổi giấy phép, mã số thuế hoặc thông tin pháp lý, vui lòng gửi yêu cầu đến Văn phòng BIHUBA để xác minh.</p><Link href="/lien-he" className="mt-4 inline-flex text-sm font-semibold text-[#0E4FAF]">Liên hệ xác minh →</Link></article><article className="rounded-[1.6rem] border border-slate-200 bg-white p-5 shadow-sm"><h2 className="text-lg font-semibold text-slate-950">Quyền sắp mở rộng</h2><p className="mt-2 text-sm leading-6 text-slate-600">Quản lý gian hàng, logo đối tác và bài viết của doanh nghiệp sẽ được bổ sung trong các bước phát triển tiếp theo.</p></article></div></section>;
}
