import { requireAdminPage } from "@/lib/admin-auth";
import { getOperationsSummary, getRfqs, getTransactions } from "@/lib/operations";

export default async function PrintReportPage() {
  await requireAdminPage("/admin/reports");
  const [summary, rfqs, transactions] = await Promise.all([getOperationsSummary(), getRfqs(), getTransactions()]);
  const signingConfigured = Boolean(process.env.PDF_SIGNING_PROVIDER && process.env.PDF_SIGNING_PROFILE);
  const metrics = [["Tổng RFQ", summary.rfqTotal], ["RFQ đã ghép", summary.rfqMatched], ["Giao dịch", summary.transactionTotal], ["Doanh thu", `${summary.paidAmount.toLocaleString("vi-VN")} đ`]];
  return <main className="mx-auto max-w-5xl bg-white p-8 text-slate-900 print:max-w-none print:p-0 sm:p-10"><style>{`@media print { @page { size: A4; margin: 14mm; } .no-print { display: none !important; } }`}</style><header className="border-b-2 border-[#082a55] pb-5"><div className="flex items-start justify-between gap-5"><div><p className="text-xs font-bold uppercase tracking-[0.2em] text-[#1769e8]">Hội Doanh nghiệp Xã Bình Hưng</p><h1 className="mt-2 text-2xl font-semibold">Báo cáo điều hành BIHUBA B2B</h1><p className="mt-2 text-sm text-slate-500">Ngày xuất: {new Date().toLocaleDateString("vi-VN")}</p></div><div className="no-print rounded-xl bg-slate-100 px-4 py-2 text-sm text-slate-600">Nhấn Ctrl+P → Lưu dạng PDF</div></div></header><section className="mt-6 grid grid-cols-2 gap-3 sm:grid-cols-4">{metrics.map(([label, value]) => <div key={String(label)} className="border border-slate-200 p-4"><p className="text-xs text-slate-500">{label}</p><strong className="mt-2 block text-xl text-[#082a55]">{value}</strong></div>)}</section><section className="mt-8"><h2 className="border-b pb-2 text-lg font-semibold">RFQ gần đây</h2><table className="mt-3 w-full border-collapse text-sm"><thead><tr className="bg-slate-100 text-left"><th className="border p-2">Mã</th><th className="border p-2">Nhu cầu</th><th className="border p-2">Trạng thái</th></tr></thead><tbody>{rfqs.slice(0, 20).map((row) => <tr key={String(row._id)}><td className="border p-2">{row.code}</td><td className="border p-2">{row.title}</td><td className="border p-2">{row.status}</td></tr>)}</tbody></table></section><section className="mt-8"><h2 className="border-b pb-2 text-lg font-semibold">Giao dịch gần đây</h2><table className="mt-3 w-full border-collapse text-sm"><thead><tr className="bg-slate-100 text-left"><th className="border p-2">Mã</th><th className="border p-2">Hội viên</th><th className="border p-2 text-right">Số tiền</th></tr></thead><tbody>{transactions.slice(0, 20).map((row) => <tr key={String(row._id)}><td className="border p-2">{row.code}</td><td className="border p-2">{row.memberName}</td><td className="border p-2 text-right">{Number(row.amount).toLocaleString("vi-VN")} đ</td></tr>)}</tbody></table></section><footer className="mt-12 grid grid-cols-2 gap-8 border-t pt-6 text-center text-sm"><div><p className="font-semibold">Người lập báo cáo</p><div className="h-20" /><p className="border-t pt-2 text-slate-500">Ký, ghi rõ họ tên</p></div><div><p className="font-semibold">Đại diện BIHUBA</p><div className="h-20" /><p className="border-t pt-2 text-slate-500">{signingConfigured ? "Sẵn sàng ký số qua hệ thống đã cấu hình" : "Ký tay hoặc chờ cấu hình chứng thư số"}</p></div></footer></main>;
}
